Consolidation of the programming exam info resolves #146
softwareconstruction240/softwareconstruction pull request #148
Opened 2024-10-18 17:56 UTC by Truthwatcher64

This brings all the available info for the programming exam to github.

It also adds a section for using Linux for the exam

resolves #146

2024-10-19 16:26 UTC, frozenfrank commented
@Truthwatcher64 Can you update the PR description to specifically say "resolves #146"? That special keyword links the this PR to the Issue so that they are closed together. Unfortunately, I don't have permission to make that edit myself, and the special keyword is only effective if it's in the PR description (not in a comment like this).

2024-10-19 18:24 UTC, frozenfrank commented
@Truthwatcher64 I see that you changed the title of the PR, but can you change the description?

<img width="931" alt="Screenshot 2024-10-19 at 12 24 45 PM" src="https://github.com/user-attachments/assets/ff992d44-eafb-4ae7-90e5-fd2ffd2dc4f7">

2024-10-21 14:43 UTC, leesjensen commented on instruction/programming-exam/programming-exam.md
> +You should also open the Javadoc in a web browser tab and the [chess phase-0 specification](https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/0-chess-moves/chess-moves.m
Extra space at the end of the paragraph

2024-10-21 14:47 UTC, leesjensen commented on instruction/programming-exam/programming-exam.md
> +⚠ The exam is not open until midnight the day of the exam. It closes at 5, so make sure that you start with enough time.
Having a different ending time from all the other assignments has caused significant confusion and frustration for many learners. We are considering changing this to midnight and this reference will create a duplication of the deadline that might be incorrect.

2024-10-21 14:57 UTC, leesjensen commented on instruction/programming-exam/programming-exam.md
> +If you are going to make handwritten notes while working have a blank sheet of paper ready to show to the camera at the start of the exam.
Do we need this? Can't they just take notes in a markdown file?

2024-10-21 14:58 UTC, leesjensen commented on instruction/programming-exam/programming-exam.md
> +This programming exam is a re-creation of your [chess phase-0](https://github.com/softwareconstruction240/softwareconstruction/blob/main/chess/0-chess-moves/chess-moves.md) assignment, but under time
"No notes or other resources ..." Sets up the expectation that there are some type of "notes" that are allowed. I think we are getting rid of that possibility.

2024-10-21 15:01 UTC, leesjensen commented
This is really good and has great information in it. It is really good to get this all in one place and make it easy to maintain and update and so I am excited to get it into GitHub. It is also something that is really important to get right. Perhaps we should get multiple reviewers on this before we finalize it.

2024-10-24 18:00 UTC, frozenfrank requested changes
Please give public access to your fork (or directly give me access) so that I can propose other adjustments to the verbiage and formatting of the document

2024-11-26 22:03 UTC, leesjensen commented
@Truthwatcher64 - Now that we have passed the last retake, I think we can merge this. Do you want to resolve @frozenfrank 's comments? Also this seems to be a dead page. There is a link to @jerodw's schedule, but I believe we want to make this part of the core instruction. Can we add a link from the [modules page](https://github.com/softwareconstruction240/softwareconstruction/blob/main/instruction/modules.md)?

2024-12-05 19:47 UTC, merged